metasheet: 'metasheet.csv'
bwa_index: /data/static_libraries/bwa_indices/hg19/hg19.fa
conservation: /data/static_libraries/conservation/hg19/vertebrate
geneTable: /data/static_libraries/ucsc/hg19.refGene
DHS: /data/static_libraries/DHS/DHS_hg19.bed
velcro_regions: /data/static_libraries/vecro/wgEncodeHg19ConsensusSignalArtifactRegions.bed
chrom_lens: /data/static_libraries/chromLen/hg19.len

samples:
  JG1A_ER:
    - data/JG1A-ERChIP_9M.R1.fastq.gz
    - data/JG1A-ERChIP_9M.R2.fastq.gz
  JG1A_Input:
    - data/JG1A-Input_7.75M.R1.fastq.gz
    - data/JG1A-Input_7.75M.R2.fastq.gz



