#NOTE: you won't typically have to change the following two lines!
metasheet: 'metasheet.csv'
ref: "chips/ref.yaml"

#Tell us what assembly to use (!! MUST be defined in chips/ref.yaml !!)
assembly: hg19

#ALIGNER: if you want to use bowtie2, set your aligner as 'bwt2'
#OTHERWISE leave it as 'bwa' 
aligner: 'bwa'
#aligner: 'bwt2'

#NOTE: optional contamination panel to check sample contamination against
#Each element should be a path to the INDEX for the aligner you want to use
#The name of the file will be used in the table report, 
#e.g. /some/path/to/BWA/e_coli.fasta will be reported as "e_coli"
contamination_panel:
  #- /some/path/to/BWA/e_coli.fasta
  #- /some/path/to/BWA/yeast.fasta
  - /data/static_libraries/bwa_indices/hg19/hg19.fa
  - /data/static_libraries/bwa_indices/e_coli/e_coli.fasta
  - /data/static_libraries/bwa_indices/S_cerevisiae/S_cerevisiae.fa

#NOTE: optional CNV analysis using QDNAseq R pkg
cnv_analysis: false

# DEFINE the samples- each sample should have a name, e.g. SAMPLE1
# and a path to the input file, e.g. data/sample1.fastq.gz
# VALID INPUTS: fastq, fastq.gz, bam
# NOTE: for PAIRED-END fastq/fastq.gz, give both pairs to the sample:
# SAMPLE_1_PE:
#   - data/sample1_pair1.fastq
#   - data/sample1_pair2.fastq
# WARNING: DO not mix Paired-END and Single-End samples!!!
samples:
  SAMPLE1:
    - data/sample1.fastq.gz
  SAMPLE2:
    - data/sample2.fastq.gz
